### PR TITLE
German

### PR DESCRIPTION
**Pull request by Ar2rZ**
German keyboard layout

### CODE REVIEW

**Comment by JuliusSweetland** [comment]
Hey. Git and GitHub can make things a bit tricky sometimes, and this is one of those times! I'm not sure why, but your pull request contains a LOT of file changes that are already on the "localisa" branch, plus your old test commits, which I would like to avoid merging as they then become available for everyone.

Unfortunately there is no easy way to merge your commits and then delete commits to clean up. There might be a way for you to do it, but cleaning up git is tricky and the GitHub website makes it even harder! I think the easiest thing to do is:

1.Make a local copy of your changes (the new German keyboard) and **make sure you actually copy these files somewhere else on disk**.
2.Delete your GitHub OptiKey repo (https://help.github.com/articles/deleting-a-repository/). 
3.Fork my repo again.
4.Copy your forked repo to your computer using the GitHub application. You might have to delete the local copy of your repo from your computer and remove it from the GitHub application before you re-add it again. This lets you start from scratch again.
5.Manually apply your new German keyboard again.
6.Create a new commit with message "Adds new German Alpha and ConversationAlpha keyboards" or something like that.
7.Sync your commit up to GitHub
8.Submit a pull request.

Phew! I know this is convoluted, but git is a really tricky beast and it's important to keep "test" commits etc out of the main OptiKey repo's history as everyone will get them if I merge them in.

P.S. This is the second time I've rejected a pull request from you - please don't take it personally. I use git professionally at work and it's taken me about 9 months to get even slightly comfortable with it. You're doing great work and I very much appreciate it.

**Comment by JuliusSweetland** [comment]
P.P.S. Make sure you make changes to your forked "localisa" branch and that you pull the latest changes from my "localisa" branch before you submit the pull request. This allows you to fix any merge issues before you submit and then I just have to eye-ball the changes and click the "Merge" button and bingo!

**Comment by JuliusSweetland** [comment]
If you have problems please let me know - I **can** potentially resolve these issues for you, but I'm exhausted today and it might take me a few days before I can even look at it.

**Comment by Ar2rZ** [comment]
no worries, i will clean my repo and add changes for Germany again... i am not expecting, that i do everything right. specially, in the beginning, i did lot of changes and test on this  branch.
at work i am using PerForce, i was expecting kind  of similar behavior, only the last commits are visible. but GitHub is a bit more complicated, a bit more thing needs to be aware about.

**Comment by JuliusSweetland** [comment]
Yes it's tricky. I'm here if you have questions.

**Pull request closed without merging**
