### PR TITLE
Issue 14 - Write unit tests

### PR DESCRIPTION
**Pull request by padmo**
Hi Julius,

I just stumbled on your project via Reddit Originals, looked cool and it's open source in .NET (so no extra technology barrier for me), so I checked it out because I wanted to try to contribute to an open source project for a while now, see what i's like :)

This pull request contains changes related to https://github.com/JuliusSweetland/OptiKey/issues/14
The goal is to capture the current behavior in automated tests, so any unintentional changes are flagged and you get more confidence to refactor and add new features, minimizing regressions.

To demonstrate my approach, I have started with the MainViewModel constructor.
The test names are purposefully verbose, aiming to focus on the functional instead of the technical, hopefully making them as clear and meaningful as possible:
1. Namespace contains the subject (e.g. MainViewModelSpecifications)
2. The class name contains the part of the subject under test in a given scenario (e.g. WhenConstructGivenConversationOnlyMode)
3. The test method contains the specification (e.g. ThenWindowShouldBeMaximised)

Expected behavior is specified as should, since requirements can change, but you then explicitly have to change or remove the test.

Notes:
1. To be able to setup different scenarios, I made the internals of JuliusSweetland.OptiKey visible to the test project
2. I added a TestBase class, to streamline the style of the tests
3. I couldn't test all scenarios (AttachScratchpadEnabledListener is not tested, AttachKeyboardSupportsMultiKeySelectionListener is partially tested)

If you're interested in continuing on this path, let me know, I'll see what I can contribute :)

### CODE REVIEW

**Comment by JuliusSweetland** [comment]
I very much like what you've done here! Thank you. I am very interested in continuing down this path if you have any more time?

**Comment by padmo** [comment]
Cool, then I intend to do some more :)

I saw GitHub suggests for collaborating to work on a topic branch and send a pull request for this (https://help.github.com/articles/using-pull-requests/).
I had already merged to master, that's why my pull request came in on master.
But I'll keep the next changes on a branch and let you merge to master, so you can keep an overview, in case there are a lot of different changes going on.

**Comment by JuliusSweetland** [comment]
That sounds ideal. Do I need to create a source branch for you or will you
branch off master? If it's the latter would your pull request not be back
onto my master branch anyway?

**Comment by padmo** [comment]
I'm not sure actually, but it does make sense for you to create the branch, so you can go ahead.

**Comment by JuliusSweetland** [comment]
Ok, I've created the "UnitTests" branch for continued development. I'll update from master whenever anything major changes, as I do for the localisation branches.

**Pull request merged**
