### PR TITLE
fixed 4 more strings

### PR DESCRIPTION
**Pull request by ninehundred1**
I think that should be all. I don't know about the error messages and all that, but as those are whole sentences, they should be fine and the context should be clear.

### CODE REVIEW

**Comment by JuliusSweetland** [comment]
Looks good. I have identified 2 more strings which are causing some icons to be displayed smaller than they need to be and have just submitted the following change (breaking "Add to dictionary" and "Re-calibrate" one more time: c2b920006abb006140d3442652d25db5e41a7678

**Comment by ninehundred1** [comment]
So there is a change I need to do with  those? I can just search for those in the German source file?

**Comment by JuliusSweetland** [comment]
You don't need to do anything. If you take a look at that commit that I
linked in my comment you'll see what I changed. I've also been advised by
one of my German users (who I gave an early copy to) to do the following.
Let me know if you disagree, otherwise I'll try to make these changes
tomorrow:

1. The enter key must be labelled " Eingabe" ( spelling error)

2. The back word key should be labelled "Wort Zurück"

3. In the main menue the labels for "Transparenz erhöhen" and " Transparenz
verringern" ( meaning reducing transparency) should be swapped.

4. Please sort the German diacritics like this: ä ö ü ß

**Comment by ninehundred1** [comment]
Did you give your user the commit from last night? I fixed the Wort  
zurück, and will look at the others, which look they need changing. I  
can do that tomorrow.

**Comment by JuliusSweetland** [comment]
He may be commenting on the previous version. I'll take a look tomorrow. At
the rugby

**Comment by ninehundred1** [comment]
I checked the mistakes the german user has reported and made a pull
request. see below (especially 3).

1. The enter key must be labelled " Eingabe" ( spelling error)

-fixed



2. The back word key should be labelled "Wort Zurück"

-fixed that last round



3. In the main menue the labels for "Transparenz erhöhen" and " Transparenz
verringern" ( meaning reducing transparency) should be swapped.

-this is wrong and correct. The strings are correctly translated from the
english original, but he is right, they are swapped. Decrease transparency
in the current case makes the window be more see through, which is actually
an increase in the transparency. So you might have to look at the original
to fix that and probably just swap the GUI button handle around. I didn't
notice because decrease made it less present, which I assumed was correct.



4. Please sort the German diacritics like this: ä ö ü ß

-I assume he means the keyboard, which is not in that order. How can I do
that, is that something Arthur needs to do, it is part of the diacritic
keyboard

**Comment by JuliusSweetland** [comment]
Great stuff. Don't worry about number 4 - that's one for me. I move the
current language diacritics before all the rest and he's just asking me to
change the order a bit. I'll fix that tonight or tomorrow night and prepare
a new pre release.

**Comment by ninehundred1** [comment]
I think after that is should be fine.

**Comment by JuliusSweetland** [comment]
Excellent. I'll try to find time tonight then.

**Pull request merged**
