### PR TITLE
Localisa

### PR DESCRIPTION
**Pull request by ninehundred1**
Chose the shorter German dictionary and fixed the '?' with the appropriate umlauts.

### CODE REVIEW

**Comment by JuliusSweetland** [comment]
Hey. Git and GitHub can make things a bit tricky sometimes, and this is one of those times! Your pull request contains your original attempt to migrate old user dictionaries, which means I cannot merge it in to my "localisa" branch as the files are clashing.

Unfortunately there is no easy way to merge your commits and then delete commits to clean up. There might be a way for you to do it, but cleaning up git is tricky and the GitHub website makes it even harder! It might be easier to locally back up your new German dictionary file and then scrap everything (including deleting your fork of the repo) and then fork a new one and put your german dictionary back in again. It sounds like overkill, but there isn't really an easy way to delete individual commits that have been sync'd with the GitHub site (you can try - there's a rough guide here: http://stackoverflow.com/questions/448919/how-can-i-remove-a-commit-on-github). Otherwise the "fresh start" steps would be:

1.Make a local copy of your changes (the new German dictionary file) and **make sure you actually copy these files somewhere else on disk**.
2.Delete your GitHub OptiKey repo (https://help.github.com/articles/deleting-a-repository/). 
3.Fork my repo again.
4.Copy your forked repo to your computer using the GitHub application. You might have to delete the local copy of your repo from your computer and remove it from the GitHub application before you re-add it again. This lets you start from scratch again.
5.Manually apply your new German keyboard again.
6.Create a new commit with message "Adds new German dictionary" or something like that.
7.Sync your commit up to GitHub
8.Submit a pull request.

Phew! I know this is convoluted, but git is a really tricky beast and it's important to keep "test" commits etc out of the main OptiKey repo's history as everyone will get them if I merge them in.

P.S. This is the second time I've rejected a pull request from you - please don't take it personally. I use git professionally at work and it's taken me about 9 months to get even slightly comfortable with it. You're doing great work and I very much appreciate it.

Julius

**Comment by JuliusSweetland** [comment]
If you have problems please let me know - I **can** potentially resolve these issues for you, but I'm exhausted today and it might take me a few days before I can even look at it.

**Comment by ninehundred1** [comment]
I am new to this and still learning, so I really appreciate the help. I
tried to get the localisa branch, as that was the one that had the
canditate dictionaries (the master doesn't), so it took a while to find out
how to get that and not the master (I am using git shell). Then I wanted to
push it back to my forked version of localisa, and not master, so I did a
few wrong pushes, that might have been the problem. I think I found the
right command and deleted all and started from scratch. And I think it
works now.
Don't worry about rejecting stuff, as I said, i am completely new and make
a lot of mistakes because of that, so I kind of expect to screw up with
those things at the moment.
It is good that I can help, I would like to help more of course, because I
really respect the work and time you put in there.
So take a weekend off or something.

**Comment by JuliusSweetland** [comment]
I think I need to. I'm exhausted and will probably start making mistakes.
Unfortunately I've got too much on! I'm speaking with the head of the
Stephen Hawking Intel project this evening and have a Reddit producer
flying over tomorrow to spend 3 days with me. This project might just kill
me!

**Comment by ninehundred1** [comment]
Take that Reddit guy out and watch some Rugby, what else would you do over
3 days, can't talk business all the time and I am sure the people on here
are fine to wait until Monday to move forward.
I am sure you know it is worth the effort, and you see it all paying off,
so you obviously did a very good job and if it works out, will make the
life better for some people.

**Comment by JuliusSweetland** [comment]
Good advice. I think I'll take it.

**Pull request closed without merging**
